language: python
python: "3.6"
install:
  - "pip install ."
  - "pip install pytest"
  - "pip install coverage"
  - "pip install coveralls"
script: 'coverage run --source "." --omit "setup.py,tests/speed_tests.py" -m pytest'
after_success: coveralls
