#!/bin/bash
# Automated Codebase Cleanup Script
# SAFE TO RUN - All active files protected
# Generated: 2025-01-20

set -e  # Exit on error

echo "🧹 PokerGeek.ai Codebase Cleanup Script"
echo "======================================="
echo ""

# Check if we're in the right directory
if [ ! -f "sophisticated-engine-server.js" ]; then
    echo "❌ Error: Must run from poker-engine directory"
    exit 1
fi

# Create backup first
echo "📦 Creating backup branch..."
git checkout -b backup-before-cleanup-$(date +%Y%m%d-%H%M%S) 2>/dev/null || echo "⚠️  Branch already exists, continuing..."
git add .
git commit -m "chore: backup before cleanup" 2>/dev/null || echo "ℹ️  Nothing to commit"
echo "✅ Backup created"
echo ""

# Ask for confirmation
echo "⚠️  This will delete ~115 deprecated files"
echo "📋 Review CLEANUP_PLAN.md for full details"
echo ""
read -p "Continue with cleanup? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "❌ Cleanup cancelled"
    exit 0
fi

echo ""
echo "🗑️  Starting cleanup..."
echo ""

# Phase 1: Delete MD files
echo "Phase 1/5: Removing deprecated documentation..."
rm -f AUTH_ARCHITECTURE.md AUTH_FIX_COMPLETE.md AUTH_FLOW_FIXED.md \
   AUTH_IMPLEMENTATION_PLAN.md AUTH_MODAL_FIXED.md AUTH_SYSTEM_UNIFIED.md \
   GUEST_AUTH_SETUP.md GUEST_LOGIN_FIX.md GUEST_UUID_FIX.md \
   TESTING_GUIDE_AUTH.md

rm -f DAY1_COMPLETION_SUMMARY.md DAY1_SUCCESS_SUMMARY.md \
   DAY2_COMPLETION_SUMMARY.md DAY3_COMPLETION_SUMMARY.md \
   DAY4_COMPLETION_SUMMARY.md DAY5_COMPLETION_SUMMARY.md \
   WEEK1_COMPLETE_SUMMARY.md WEEK_2_COMPLETE.md

rm -f CURRENT_STATUS.md FINAL_STATUS.md PHASE1_CRITICAL_STATUS.md \
   PROJECT_INDEX_AND_READINESS.md READY_TO_PLAY.md READY_TO_TEST.md \
   WHATS_FIXED_TODAY.md FINAL_FIX_SUMMARY.md SUPER_SAIYAN_FIXES_COMPLETE.md

rm -f API_ENDPOINTS_PLAN.md COMPREHENSIVE_BUILD_PLAN.md \
   FRIEND_SYSTEM_IMPLEMENTATION_PLAN.md FRONTEND_UI_PLAN.md \
   IMPLEMENTATION_ROADMAP.md REFACTOR_EFFORT_BREAKDOWN.md \
   SCALABLE_ARCHITECTURE_BLUEPRINT.md supabase-integration-plan.md \
   USER_MANAGEMENT_PLAN.md

rm -f ANALYSIS_SUMMARY.md APPLICATION_INTEGRATION_MAP.md \
   ARCHITECTURE_FLOW_ANALYSIS.md DATABASE_ADVISOR_REPORT.md \
   DATABASE_SCHEMA_DIAGRAM.md DATABASE_TECHNICAL_DEEP_DIVE.md \
   DISCONNECT_IDENTIFIED.md EVENT_SOURCING_AFFECTED_FILES.md \
   FILE_INVENTORY.md

rm -f APPROVAL_FLOW_COMPLETE.md CLEAR_BROWSER_CACHE.md \
   COMPLETE_FLOW_FIXED.md COMPLETE_GAME_FLOW.md \
   DEBUG_BETTING_ROUND.md FOREIGN_KEY_FIX.md \
   GAME_LOGIC_WIRED.md GUEST_APPROVAL_TEST.md \
   IMPLEMENTATION_COMPLETE.md NAVBAR_FIX_V2.md \
   POKERUI_MIGRATION_COMPLETE.md PORT_TABLE_FUNCTIONALITY.md \
   REDIRECT_TO_TABLE_COMPLETE.md SCALING_IMPLEMENTATION_SUMMARY.md \
   SINGLE_PAGE_FLOW_COMPLETE.md SKIP_OLD_UI_FIX.md \
   USERNAME_LINGERING_FIX.md

rm -f PHASE1_TESTING_GUIDE.md QUICK_TEST_GUIDE.md \
   TEST_MIGRATION.md TEST_NOW.md TEST_SOCIAL_FEATURES.md

rm -f SUPABASE_SETUP.md EXECUTIVE_SUMMARY.md \
   FINAL_READINESS_CHECK.md QUICK_REFERENCE.md

echo "✅ Documentation cleanup complete"

# Phase 2: Delete deprecated scripts
echo "Phase 2/5: Removing deprecated scripts..."
rm -f add-missing-functions.js analyze-current-db.js audit-database.js \
   check-db-state.js check-tables.js create-test-user.js \
   drop-guest-constraints.js drop-rooms-constraint.js \
   drop-user-profiles-constraint.js test-event-bus.js \
   test-event-store.js test-scaling-features.js

rm -f fix-auth-now.sql

echo "✅ Script cleanup complete"

# Phase 3: Delete duplicate public files
echo "Phase 3/5: Removing duplicate public files..."
rm -f public/index.html 2>/dev/null || echo "ℹ️  public/index.html not found"
rm -rf public/pages/playing-cards-master/ 2>/dev/null || echo "ℹ️  playing-cards-master not found"

echo "✅ Public file cleanup complete"

# Phase 4: Delete nested duplicate
echo "Phase 4/5: Removing nested duplicate directory..."
rm -rf poker-engine/poker-engine/ 2>/dev/null || echo "ℹ️  Nested directory not found"

echo "✅ Nested directory cleanup complete"

# Phase 5: Commit changes
echo "Phase 5/5: Committing cleanup..."
git add .
git commit -m "chore: remove deprecated docs, scripts, and duplicate files

- Remove 44 outdated MD documentation files
- Remove 10 deprecated one-time scripts
- Remove duplicate card images (58 files)
- Remove nested duplicate poker-engine directory
- Keep all active server, source, and public files
- Keep essential docs: NAVBAR_SYSTEM_GUIDE.md, QUICK_START.md, TESTING_GUIDE.md
- Saved ~27 MB of disk space

Generated by: scripts/cleanup-codebase.sh"

echo "✅ Changes committed"
echo ""

echo "🎉 Cleanup complete!"
echo ""
echo "📊 Summary:"
git diff --stat HEAD~1 HEAD | tail -n 1
echo ""

# Verification
echo "🔍 Verification Steps:"
echo "1. Start server: npm start"
echo "2. Test routes:"
echo "   - http://localhost:3000/"
echo "   - http://localhost:3000/play"
echo "   - http://localhost:3000/game"
echo "3. If issues occur, rollback: git reset --hard HEAD~1"
echo ""
echo "💾 Backup branch created for safety"
echo "✅ Ready to push: git push origin main"

